### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by danielgoodwin97** [BuXXe/PARAM.PFD-PS3-Demons-Souls-Savegame-Tool#2]
This isn't an issue - I just couldn't find another way of contacting you.

I just wanted to say thank you! I've been messing around with old save editors for hours trying to change my character from female to male because there was some armour I had been shooting for which was gender locked and I had no idea that gender locked armour was even a thing.

Your tools were by far the easiest to use - the rest just didn't work at all haha.

Is there any way I can drop you a few bucks?

Cheers,
Dan.

**Comment by BuXXe** [comment]
Heyho, I am happy that my work and especially the documentation helped someone :). You really dont need to but if you want to give me more than a thank you, i got my paypal at: ****

**Comment by danielgoodwin97** [comment]
I've dropped you a little bit of money. Thanks again bro! ☺️
